version: "3"
services:
    nginx:
        image: nginx:latest
        container_name: rma-nginx
        restart: always
        ports: 
        - "80:80"
        volumes:
            - ./www:/www
            - ./site.conf:/etc/nginx/conf.d/site.conf
        links:
            - php
    php:
        image: php:7.3-fpm
        command:
              - /bin/sh
              - -c
              - |
                 docker-php-ext-install mysqli 
                 echo "extension installed.....starting php-fpm........................................"
                 php-fpm
        container_name: rma-php-fpm
        volumes:
        - ./www:/www
        links:
            - db
    db:
        image: mysql:5.7
        container_name: rma-mysql
        ports:
        - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: Uws012aQ=!
            MYSQL_DATABASE: br
